holachatsproj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from holachatsweb import views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^holachatsweb/',include('holachatsweb.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^privacy/$', views.privacy, name='privacy'),
    url('avatar/', include('avatar.urls')),
]


urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
		urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
		urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

holachatsweb/urls.py
from django.conf.urls import url
from holachatsweb import views

app_name = 'holachatsweb'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

holachatsweb/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	portfolio_url = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

	def __str__(self):
		return self.user.username

holachatsweb/forms.py
from django import forms
from holachatsweb.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('first_name', 'last_name', 'username', 'password', 'email')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_url', 'profile_pic')

holachatsweb/views.py
from django.shortcuts import render
from holachatsweb.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
	return render(request, 'holachatsweb/index.html')

@login_required
def special(request):
	return HttpResponse("You are logged in!")

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))


def register(request):
	registered = False
	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(data=request.POST)
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			if 'profile_pic' in request.FILES:
				print('found it')
				profile.profile_pic = request.FILES['profile_pic']
			profile.save()
			registered = True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()
	return render(request, 'holachatsweb/registration.html',
							{'user_form':user_form,
							'profile_form':profile_form,
							'registered':registered})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))
			else:
				return HttpResponse("Your account was inactive.")
		else:
			myMessage = "You have entered a wrong login detials"
			print("Someone tried to login and failed.")
			print("They used username: {} and password: {}".format(username,password))
			return render(request,'holachatsweb/index.html', {'myMessage':myMessage})
	else:
		return render(request, 'holachatsweb/login.html', {})


@login_required
def profile(request):
	return render(request, 'holachatsweb/profile.html', {})

def privacy(request):
	return render(request, 'holachatsweb/privacy.html', {})

templates/avatar/change.html
{% extends "avatar/change.html" %}

{% load static %}
{% load avatar_tags %}

{% block title %}{{ title }} | {{ site_title|default:_('Avatar site admin') }}{% endblock %}

{% block content %}
<div style="text-align: center;">
<h1 id="site-name">
    <a href="{% url 'admin:index' %}">
        <img src="{% static 'imgs/holachats-just-logo.png' %}" height="40px" /><span style="font-weight: bold; padding-left: 20px;"> HolaCHATS Live Chats Support 
    </a>
    <a style="padding-left: 40px; color: #343a40" href="{% url 'index' %}"><img src="{% static 'imgs/home-solid.svg' %}" style="width: 30px"> Back to homepage</a>
</h1>
	{% include 'avatar/add.html' %}
</div>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/holachatsweb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="live chat, chat support, live chat support assistance, holachats, hellochats, chat agents, customer chat agents">

    <!--AOS Animate -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!--Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">

    <!--Google font -->
    <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 

    <!--Link to enternal stylesheet -->
    <link rel="stylesheet" href="{% static 'css/mainstyle.css' %}">

    <!--Favicon -->
    <link rel="icon" type="icon/image" href="{% static 'imgs/holachats-just-logo.png' %}">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <img src="{% static 'imgs/holachats-logo-text-2.png' %}" class="navbar-brand" href="#">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Hola<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}#withoutLiveChat">Without Livechat</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Our Offer
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'index' %}#whatholaChatDelivers">24/7 LiveChat Support</a>
              <a class="dropdown-item" href="{% url 'index' %}#howOuSolutionWorks">How It Works</a>
              <!-- <div class="dropdown-divider"></div> -->
              <a class="dropdown-item" href="{% url 'index' %}#keyBenefits">Key Benefits</a>
              <a class="dropdown-item" href="{% url 'index' %}#keyBenefits">How It Helps</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              HolaCHATS
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'index' %}#aboutUs">About Us</a>
              <a class="dropdown-item" href="#">Mission</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Vision</a>
              <a class="dropdown-item" href="#">Roadmap</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
          {% if user.is_authenticated and user.is_staff %}

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fas fa-search"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}#contactSales">Contact Sales</a>
          </li>
          {% endif %}

          {% if user.is_authenticated %}
          {% load avatar_tags %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'avatar_change' %}"><i>{% avatar user 30 class="rounded-circle img-responsive" id="user_avatar" %}</i> {{ user.first_name }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}"><i class="fas fa-tachometer-alt"></i> Dashboard</a>
          </li>
              {% if user.is_staff %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}"><i class="fas fa-user-lock"></i> Admin</a>
                </li>
              {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'holachatsweb:user_login' %}">Login</a>
          </li>
          <div class="signup-border"></div>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'holachatsweb:register' %}">Sign up <i class="fas fa-arrow-right ml-1"></i></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block content %}

    {% endblock %}
    <footer class="container">
      <div class="row row-1">
        <div class="col-lg col-md">
          <h5>Why holaCHATS</h5>
          <ul>
            <li><a href="#">Customer Friendly</a></li>
            <li><a href="#">Fast &amp; secured</a></li>
            <li><a href="#">Customer Satisfaction</a></li>
          </ul>
        </div>
        <div class="col-lg col-md">
          <h5>Product</h5>
          <ul>
            <li><a href="#">Classic</a></li>
            <li><a href="#">Premium</a></li>
            <li><a href="#">Ultimate</a></li>
          </ul>
        </div>
        <div class="col-lg col-md">
          <h5>Resources</h5>
          <ul>
            <li><a href="#">Chat Apps</a></li>
            <li><a href="#">API Init</a></li>
            <li><a href="#">Docs and Info</a></li>
          </ul>
        </div>
        <div class="col-lg col-md">
          <h5 id="demo">Contact us</h5>
          <ul>
            <li><a href="#">Sales</a></li>
            <li><a href="#">Support</a></li>
            <li><a href="#">Status</a></li>
          </ul>
        </div>
        <div class="col-lg col-md">
          <h5>Company</h5>
          <ul>
            <li><a href="#">Blog</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Careers</a></li>
          </ul>
        </div>
      </div>
      <div class="row text-center m-5">
        <div class="col-lg col-md">
          <p>&copy; 2020 holaCHATS</p>
        </div>
      </div>
      <div class="row termsPrivacy">
        <div class="col-lg col-md">
          <ul>
            <li><a href="#">Terms</a></li>
            <li><a href="{% url 'privacy' %}">Privacy</a></li>
          </ul>
        </div>
      </div>
      <a href="#"><span class="arrow float-right"><i class="fas fa-angle-double-up fa-5x"></i></span></a>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--Link to external js -->
    <script src="{% static 'js/mainjs.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
    AOS.init();
  </script>
  </body>
</html>

templates/holachatsweb/index.html
{% extends 'holachatsweb/base.html' %}
{% load static %}

{% block description %}
	Welcome to holaCHATS, we are Live Chats support sytem. We offer 24/7 live chat support to your customers, giving your customers answers to all their questions concerning your services.
{% endblock %}

{% block title %}
	holaChats | Welcome Home
{% endblock %}


{% block content %}
	<!-- {% if user.is_authenticated %}
		<h2 class="text-center m-0 p-0">Hola, {{ user.first_name }} {{ user.last_name }}</h2>
	{% endif %} -->
	<header class="text-center">
		<h1>Welcome to <img src="{% static 'imgs/holachats-logo-text.png' %}"></h1>
	</header>
	<section class="container-fluid section-1">
		<div class="row">
			<!-- <div class="col-lg-6 col-md-6 col-sm-12 clearfix first-div">
				<img src="{% static 'imgs/chat-ss-1.jpg' %}" class="float-left" data-aos="zoom-in" data-aos-duration="3000">
				<img src="{% static 'imgs/chat-ss-2.jpg' %}" class="float-right" data-aos="zoom-in-up" data-aos-duration="3000">
				<img src="{% static 'imgs/chat-ss-3.jpg' %}" class="" data-aos="zoom-out-right" data-aos-duration="3000">
				<br>
				<div class="clearfix mt-5">
					<small class="font-weight-bold">
						holaCHATS has helped our clients retain their customers running into hundreds of thousands
					</small>
				</div>
			</div> -->
			<div class="col-lg-6 col-md-6 col-sm-12">
				<img class="img-fluid" src="{% static 'imgs/holachats-bg.jpg' %}" data-aos="zoom-in" data-aos-duration="3000">
				<div class="m-3">
					<small class="font-weight-bold">
						holaCHATS has helped our clients retain their customers running into hundreds of thousands
					</small>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-12 p-5">
				<h2 class="">A new approach to faster, 24/7 websites Live Chat.</h2>
				<div class="border-bottom border-dark mt-3"></div>
				<div class="text-center" id="holaweb">
					<img src="{% static 'imgs/holachats-logo-text-2.png' %}" class="hola-logo"> <i class="fas fa-plus"></i>
					<img src="{% static 'imgs/site-generator.svg' %}" class="website-png"><span>Your Website</span>
				</div>
				<div class="text-justify">
					<p>
						With holaCHATS live chat support system, your website will have 24/7 chats agents that have studied and understood your business. Our agents are all over the globe. Presently, we support FIVE Languages
						<ul>
							<i class="fas fa-language"></i>
							<li>English</li>	
							<i class="fas fa-language"></i>
							<li>Spanish</li>
							<i class="fas fa-language"></i>	
							<li>French</li>	
							<i class="fas fa-language"></i>
							<li>Italian</li>	
							<i class="fas fa-language"></i>
							<li>Hebrew</li>	
						</ul>
					</p>
				</div>
			</div>
		</div>
	</section>
	<section class="container section-2" id="withoutLiveChat">
		<h2 data-aos="zoom-in" data-aos-duration="3000">Without Live Chat Support!</h2>
		<div class="row">
			<div class="col-lg-3 col-md-3">
				<img src="{% static 'imgs/accessible-24px.svg' %}" data-aos="fade-right" data-aos-duration="3000">
			</div>
			<div class="col-lg-3 col-md-3">
				<h3>Accessiblity Issue</h3>
			</div>
			<div class="col-lg-6 col-md-6">
				<h3>Not having Live Chat Support</h3>
				<p>
					Giving your customers ease of accessing help is paramount for the growth of your business.
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-3">
				<img src="{% static 'imgs/sentiment_very_dissatisfied-24px.svg' %}" data-aos="fade-left" data-aos-duration="3000">
			</div>
			<div class="col-lg-3 col-md-3">
				<h3>Customers Dissatisfaction</h3>
			</div>
			<div class="col-lg-6 col-md-6">
				<h3></h3>
				<p>Whether you are a business that sells goods or you render services, customer's satisfaction is a priority.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-3">
				<img src="{% static 'imgs/receipt-24px.svg' %}" data-aos="fade-up-right" data-aos-duration="3000">
			</div>
			<div class="col-lg-3 col-md-3">
				<h3>Less Sales and Less ROI</h3>
			</div>
			<div class="col-lg-6 col-md-6">
				<h3></h3>
				<p>You will want to keep your customers satisfied and keep them as returning customers as well attract more customers.<p>
			</div>
		</div>
		<div id="whatholaChatDelivers"></div>
	</section>
	<section class="container section-3">
		<h2 data-aos="zoom-in" data-aos-duration="3000">What holaCHATS delivers</h2>
		<div class="row">
			<div class="col-lg-3 col-md-3">
				<h1 class="text-center"></h1>
				<div>
					<img src="{% static 'imgs/faster-websites.svg' %}">
				</div>
				<div>
					<h4 class="font-weight-bold">Faster Response</h4>
					<p>
						We have professional Customer care agents around the world. They are available 24/7 and expereinced.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-3">
				<h1 class="text-center"></h1>
				<div>
					<img src="{% static 'imgs/secure-infrastructure.svg' %}">
				</div>
				<div>
					<h4 class="font-weight-bold">Information Security</h4>
					<p>
						With holaCHATS, the information of our clients and their customer are secured.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-3">
				<h1 class="text-center"></h1>
				<div>
					<img src="{% static 'imgs/high-scale.svg' %}">
				</div>
				<div>
					<h4 class="font-weight-bold">Remote and Cloud</h4>
					<p>
						We have professionals that understands all digital demands. We offer strictly virtual solutions.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-3">
				<h1 class="text-center"></h1>
				<div>
					<img src="{% static 'imgs/improved-developer-experience.svg' %}">
				</div>
				<div>
					<h4 class="font-weight-bold">Introduce Digital Professionalism</h4>
					<p>
						Our agents are experienced IT professionals, and can help you in all areas of IT.
					</p>
				</div>
			</div>
		</div>
		<div id="howOuSolutionWorks"></div>
	</section>
	<section class="container section-4">
		<h2 data-aos="zoom-in" data-aos-duration="3000">How Our Solution Works</h2>
		<ol>
			<li>
				<h3>
					We take an intensive study of your business
				</h3>
				<p class="text-left">
					Before we decide which of our solution is best for your business, we will take a careful and intensive study of your business; products and services.
				</p>
				<img src="{% static 'imgs/holachats-how-it-works.svg' %}" class="img-fluid">
			</li>
			<div class="row">
				<div class="col-lg-6 col-md-6">
					<li>
						<h3>
							Integration and agents assignment
						</h3>
						<p class="text-left">
							After a careful study of your business, we device stratedies and design a model to respond to visitors and customers alike. We then assign our chat agents
						</p>
					</li>
				</div>
				<div class="col-lg-6 col-md-6">
					<li>
						<h3>
							24/7 onsite LiveChat Support 
						</h3>
						<p class="text-left">
							With all setup, our agents will be live 24/7 on your website to welcome and reply to questions from your site visitors and customers.
						</p>
					</li>
				</div>
			</div>
		</ol>
		<div id="keyBenefits"></div>
	</section>
	<section class="container section-5">
		<h2 data-aos="zoom-in" data-aos-duration="3000">Key Benefits - How it helps</h2>
		<div class="row">
			<div class="col-lg-4 col-md-4">
				<h3>Organized Customer Care</h3>
			</div>
			<div class="col-lg-4 col-md-4">
				<span></span>
			</div>
			<div class="col-lg-4 col-md-4">
				<img src="{% static 'imgs/running-sites-on-webservers.svg' %}">
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-4">
				<h3>Customer's Satisfaction</h3>
			</div>
			<div class="col-lg-4 col-md-4">
				<span></span>
			</div>
			<div class="col-lg-4 col-md-4">
				<img src="{% static 'imgs/prerendered-for-speed.svg' %}">
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-4">
				<h3>High Return On Investment(ROI)</h3>
			</div>
			<div class="col-lg-4 col-md-4">
				<span></span>
			</div>
			<div class="col-lg-4 col-md-4">
				<img src="{% static 'imgs/rendered-at-runtimes.svg' %}">
			</div>
		</div>
		<div id="aboutUs"></div>
	</section>
	<section class="jumbotron jumbotron-fluid section-6">
		<div class="col-lg-12 col-md-12">
			<p>
				holaCHATS: Your sure way to 24/7 live chat support.
			</p>
			<h2>Progressive Concept. Proven Results.</h2>
			<p>
				With holaCHATS, you are guaranteed 24/7 live chat support services on your website. We deliver professional customer service solutions, keeping your customers happy and satisfied.
				<br>
				With our solutions, you are sure of these three offers:
			</p>
			<div class="row mt-5">
				<div class="col-lg-4 col-md-4">
					<img src="{% static 'imgs/undraw_calendar_dutt.svg' %}" class="img-fluid text-center">
					<h3>24/7 Live Support</h3>
					<p>
						We have professional agents around the world that are always available for quick and immediate response to site visitors
					</p>
				</div>
				<div class="col-lg-4 col-md-4 border-left border-light">
					<img src="{% static 'imgs/undraw_secure_login_pdn4.svg' %}" class="img-fluid">
					<h3>Data Security</h3>
					<p>
						With our solutions available on your site, your customers gets a real sense of belonging and human presence not bot. They are satisfied because their information is secured.
					</p>
				</div>
				<div class="col-lg-4 col-md-4 border-left border-light">
					<img src="{% static 'imgs/undraw_preferences_uuo2.svg' %}" class="img-fluid">
					<h3>High Returning Customers</h3>
					<p>
						When a customer is satisfied for a service, there is 80% tendency that they will return. And also invite others.
					</p>
				</div>
			</div>
		</div>
		<div id="contactSales"></div>
	</section>
	<section class="container section-7 border-bottom border-dark">
		<h1 data-aos="zoom-in" data-aos-duration="3000">Ready to try holaCHATS?</h1>
		<span>Get your site configured in 30 minutes!</span>
		<div>
			<button class="btn btn-lg btn-purple">Get Started Now!</button> <a href="#"><span>Or talk to our team first.<i class="fas fa-arrow-right ml-1"></i></span></a>
		</div>
		<div>
			<img src="{% static 'imgs/holachats-just-logo.png' %}" class="img-fluid">
			<p class="font-weight-bold">Stay up to date with all holaCHATS' news</p>
			<form class="form-inline">
				{% csrf_token %}
				<div class="form-group mx-sm mb-2">
				    <input type="email" class="form-control" placeholder="Email Address">
				  </div>
				  <button type="submit" class="btn btn-purple mb-2">Subscribe</button>
			</form>
		</div>
	</section>
{% endblock %}

templates/holachatsweb/login.html
{% extends 'holachatsweb/base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="jumbotron jumbotron-fluid m-5 p-5">
      <h1>Login here :</h1>
<form method="post" action="{% url 'holachatsweb:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/holachatsweb/profile.html
{% extends 'holachatsweb/base.html' %}
{% load static %}

{% block content %}
	<div class="jumbotron" style="margin-top: 120px;">
		{% load avatar_tags %}
		{% if user.is_authenticated %}
			<h1 class="text-center text-uppercase mb-5">Dear {{ user.first_name }}, below is your Profile Details</h1>
			<table class="table text-light">
			  <thead class="thead-dark">
			    <tr>
			      <th scope="col">First Name</th>
			      <th scope="col">Last Name</th>
			      <th scope="col">Username</th>
			      <th scope="col">Email Address</th>
			      <th scope="col">Profile Picture</th>
			    </tr>
			  </thead>
			  <tbody>
			    <tr>
			      <td>{{ user.first_name }}</td>
			      <td>{{ user.last_name }}</td>
			      <td>{{ user.username }}</td>
			      <td>{{ user.email }}</td>
			      <td>{% avatar user 80 class="img-fluid" id="user_avatar" %} <a href="{% url 'avatar_change' %}">Change your avatar</a></td>
			    </tr>
			  </tbody>
			</table>
		{% endif %}
	</div>

{% endblock %}

templates/holachatsweb/registration.html
{% extends "holachatsweb/base.html" %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="jumbotron jumbotron-fluid m-5 p-5">
      {% if registered %}
        <h1>Thank you for registering!</h1>
        <p style="font-size: 22px; font-family: 'Ubuntu', sans-serif;">
          You can login now
          <a href="{% url 'holachatsweb:user_login' %}"><button type="button" class="btn btn-danger">Login</button></a>
        </p>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}